name: cafe_qr_menu
description: A progressive web application which intended to show customers a qr menu. 

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  flutter_svg: ^2.0.5
  custom_refresh_indicator: ^2.0.1
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Gabriela
      fonts:
        - asset: assets/fonts/Gabriela-Regular.ttf
        
    - family: VI Moc Lan
      fonts:
        - asset: assets/fonts/VI-Moc-Lan.ttf
